/**
 * Biocode - Voice Identity & Vector Projection
 *
 * Implements the biocoding protocol:
 * 1. Extract speaker vector using sherpa-onnx
 * 2. Project vector using therapist's password-derived projection matrix
 * 3. Store projected vector for matching while preventing reverse engineering
 */

import CryptoJS from 'crypto-js';
import {SpeakerVector, BiocodeResult} from '../Model/Type';
import {Therapist} from '../Model/Therapist';

// Type definitions for sherpa-onnx (to be implemented with native module)
interface SherpaOnnxInterface {
    extractSpeakerVector(audioPath: string): Promise<SpeakerVector>;
    compareVectors(vector1: number[], vector2: number[]): Promise<number>;
}

/**
 * Projected vector result
 */
export interface ProjectedVector {
    vector: number[];
    confidence: number;
}

export class Biocode {
    private sherpaOnnx: SherpaOnnxInterface | null = null;
    private projectionMatrix: number[][] | null = null;
    private therapistUuid: string | null = null;

    /**
     * Initialize the Biocode with sherpa-onnx native module
     * @param sherpaOnnxModule - The native sherpa-onnx module instance
     */
    async initialize(sherpaOnnxModule: SherpaOnnxInterface): Promise<void> {
        this.sherpaOnnx = sherpaOnnxModule;
    }

    /**
     * Set therapist credentials and generate projection matrix
     * 
     * CRITICAL: The projection_key is NEVER stored anywhere (not in database, not in files).
     * It is ONLY generated in memory from the password when this method is called.
     * Once the session ends or the object is destroyed, the projection key is gone.
     * It can only be regenerated by calling this method again with the therapist's password.
     * 
     * @param therapist - Therapist model instance
     * @param password - Therapist password (used to derive projection key in memory only)
     */
    setTherapistCredentials(therapist: Therapist, password: string): void {
        this.therapistUuid = therapist.uuid;
        
        // Get projection key from therapist model
        // The key is generated in memory only and NEVER stored
        const projectionKey = therapist.getProjectionKey(password);
        
        // Generate deterministic projection matrix from key
        // The matrix is stored in memory only for this session
        this.projectionMatrix = this.generateProjectionMatrix(projectionKey);
    }

    /**
     * Generate a deterministic projection matrix from a key
     * Uses the key as a seed for a pseudo-random number generator
     * @param key - Projection key (derived from password)
     * @param inputDim - Input vector dimension (default: 192, typical for speaker vectors)
     * @param outputDim - Output vector dimension (default: 128, reduced for privacy)
     * @returns Projection matrix [outputDim x inputDim]
     */
    private generateProjectionMatrix(
        key: string,
        inputDim: number = 192,
        outputDim: number = 128,
    ): number[][] {
        // Use key to seed a deterministic RNG
        const seed = this.hashToNumber(key);
        const matrix: number[][] = [];

        // Simple LCG (Linear Congruential Generator) for deterministic randomness
        let state = seed;
        const a = 1664525;
        const c = 1013904223;
        const m = Math.pow(2, 32);

        for (let i = 0; i < outputDim; i++) {
            matrix[i] = [];
            for (let j = 0; j < inputDim; j++) {
                state = (a * state + c) % m;
                // Normalize to [-1, 1] range
                const value = (state / m) * 2 - 1;
                matrix[i][j] = value;
            }
        }

        // Orthonormalize the matrix to preserve distances better
        return this.orthonormalize(matrix);
    }

    /**
     * Convert hash string to a number seed
     */
    private hashToNumber(key: string): number {
        let hash = 0;
        for (let i = 0; i < key.length; i++) {
            const char = key.charCodeAt(i);
            hash = ((hash << 5) - hash) + char;
            hash = hash & hash; // Convert to 32-bit integer
        }
        return Math.abs(hash);
    }

    /**
     * Orthonormalize matrix using Gram-Schmidt process
     * This helps preserve distance relationships in the projected space
     */
    private orthonormalize(matrix: number[][]): number[][] {
        const rows = matrix.length;
        const cols = matrix[0].length;
        const orthonormal: number[][] = [];

        for (let i = 0; i < rows; i++) {
            let v = [...matrix[i]];

            // Subtract projections onto previous vectors
            for (let j = 0; j < i; j++) {
                const dot = this.dotProduct(v, orthonormal[j]);
                for (let k = 0; k < cols; k++) {
                    v[k] -= dot * orthonormal[j][k];
                }
            }

            // Normalize
            const norm = Math.sqrt(this.dotProduct(v, v));
            if (norm > 0.0001) {
                for (let k = 0; k < cols; k++) {
                    v[k] /= norm;
                }
            }

            orthonormal.push(v);
        }

        return orthonormal;
    }

    /**
     * Calculate dot product of two vectors
     */
    private dotProduct(v1: number[], v2: number[]): number {
        let sum = 0;
        for (let i = 0; i < v1.length; i++) {
            sum += v1[i] * v2[i];
        }
        return sum;
    }

    /**
     * Project a vector using the projection matrix
     * @param vector - Original vector to project
     * @returns Projected vector
     */
    private applyProjection(vector: number[]): number[] {
        if (!this.projectionMatrix) {
            throw new Error(
                'Projection matrix not set. Call setTherapistCredentials() first.',
            );
        }

        const outputDim = this.projectionMatrix.length;
        const inputDim = vector.length;

        if (this.projectionMatrix[0].length !== inputDim) {
            throw new Error(
                `Vector dimension ${inputDim} does not match projection matrix input dimension ${this.projectionMatrix[0].length}`,
            );
        }

        const projected: number[] = [];

        for (let i = 0; i < outputDim; i++) {
            let sum = 0;
            for (let j = 0; j < inputDim; j++) {
                sum += this.projectionMatrix[i][j] * vector[j];
            }
            projected.push(sum);
        }

        return projected;
    }

    /**
     * Extract speaker vector from audio file
     * @param audioPath - Path to the audio file
     * @returns Speaker vector with confidence score
     */
    async extractSpeakerVector(audioPath: string): Promise<SpeakerVector> {
        if (!this.sherpaOnnx) {
            throw new Error(
                'Biocode not initialized. Call initialize() first.',
            );
        }

        try {
            const result =
                await this.sherpaOnnx.extractSpeakerVector(audioPath);
            return result;
        } catch (error) {
            throw new Error(`Failed to extract speaker vector: ${error}`);
        }
    }

    /**
     * Calculate cosine similarity between two speaker vectors
     * @param vector1 - First speaker vector
     * @param vector2 - Second speaker vector
     * @returns Cosine similarity score (0-1)
     */
    async calculateCosineSimilarity(
        vector1: number[],
        vector2: number[],
    ): Promise<number> {
        if (vector1.length !== vector2.length) {
            throw new Error('Vectors must have the same length');
        }

        if (this.sherpaOnnx?.compareVectors) {
            return await this.sherpaOnnx.compareVectors(vector1, vector2);
        }

        // Fallback: Manual cosine similarity calculation
        let dotProduct = 0;
        let magnitude1 = 0;
        let magnitude2 = 0;

        for (let i = 0; i < vector1.length; i++) {
            dotProduct += vector1[i] * vector2[i];
            magnitude1 += vector1[i] * vector1[i];
            magnitude2 += vector2[i] * vector2[i];
        }

        magnitude1 = Math.sqrt(magnitude1);
        magnitude2 = Math.sqrt(magnitude2);

        if (magnitude1 === 0 || magnitude2 === 0) {
            return 0;
        }

        return dotProduct / (magnitude1 * magnitude2);
    }

    /**
     * Project speaker vector using therapist's projection matrix
     * The projected vector preserves distance relationships for matching
     * while preventing reverse engineering of the original vector
     * @param speakerVector - The extracted speaker vector
     * @returns Projected vector result
     */
    projectVector(speakerVector: SpeakerVector): ProjectedVector {
        if (!this.projectionMatrix) {
            throw new Error(
                'Projection matrix not set. Call setTherapistCredentials() first.',
            );
        }

        const projected = this.applyProjection(speakerVector.vector);

        return {
            vector: projected,
            confidence: speakerVector.confidence,
        };
    }

    /**
     * Generate patient biocode from projected vector
     * Uses the projected vector (not original) to generate a deterministic ID
     * @param speakerVector - The extracted speaker vector
     * @returns Biocode result with patient ID from projected vector
     */
    async generateBiocode(
        speakerVector: SpeakerVector,
    ): Promise<BiocodeResult> {
        if (!this.projectionMatrix) {
            throw new Error(
                'Projection matrix not set. Call setTherapistCredentials() first.',
            );
        }

        // Project the vector
        const projected = this.applyProjection(speakerVector.vector);

        // Generate deterministic biocode from projected vector
        // This ensures same voice always produces same biocode
        const vectorString = projected.join(',');
        const biocode = CryptoJS.SHA256(vectorString).toString();

        return {
            biocode,
            confidence: speakerVector.confidence,
            timestamp: Date.now(),
        };
    }

    /**
     * Process audio file and generate biocode
     * @param audioPath - Path to the audio file
     * @returns Biocode result
     */
    async processAudio(audioPath: string): Promise<BiocodeResult> {
        const speakerVector = await this.extractSpeakerVector(audioPath);
        return await this.generateBiocode(speakerVector);
    }

    /**
     * Compare two projected vectors for matching
     * Used to verify if a speaker vector matches a stored projected vector
     * @param speakerVector1 - First speaker vector
     * @param speakerVector2 - Second speaker vector (or stored projected vector)
     * @param threshold - Similarity threshold (default: 0.85)
     * @returns True if projected vectors match within threshold
     */
    async compareProjectedVectors(
        speakerVector1: SpeakerVector | ProjectedVector,
        speakerVector2: SpeakerVector | ProjectedVector,
        threshold: number = 0.85,
    ): Promise<boolean> {
        if (!this.projectionMatrix) {
            throw new Error(
                'Projection matrix not set. Call setTherapistCredentials() first.',
            );
        }

        // Project vectors if they're SpeakerVector, otherwise use as-is (already projected)
        const projected1 =
            'confidence' in speakerVector1 &&
            (speakerVector1 as SpeakerVector).vector.length >= 100
                ? this.applyProjection((speakerVector1 as SpeakerVector).vector)
                : (speakerVector1 as ProjectedVector).vector;

        const projected2 =
            'confidence' in speakerVector2 &&
            (speakerVector2 as SpeakerVector).vector.length >= 100
                ? this.applyProjection((speakerVector2 as SpeakerVector).vector)
                : (speakerVector2 as ProjectedVector).vector;

        // Calculate cosine similarity
        const similarity = await this.calculateCosineSimilarity(
            projected1,
            projected2,
        );

        return similarity >= threshold;
    }

    /**
     * Get the projected vector for storage
     * Store this in the database for later matching
     * @param speakerVector - The extracted speaker vector
     * @returns Projected vector that can be stored and used for matching
     */
    getProjectedVectorForStorage(speakerVector: SpeakerVector): ProjectedVector {
        return this.projectVector(speakerVector);
    }
}
