/**
 * Database Service
 * expo-sqlite + Drizzle ORM
 * Schema collection and database client
 */

import {drizzle} from 'drizzle-orm/expo-sqlite';
import {openDatabaseSync} from 'expo-sqlite';
import type {SQLiteTable} from 'drizzle-orm/sqlite-core';
import type {ExpoSQLiteDatabase} from 'drizzle-orm/expo-sqlite';
import {migrate} from 'drizzle-orm/expo-sqlite/migrator';
import {queueItemsTable} from '@Entity/QueueItem';
import {therapistsTable} from '@Entity/Therapist';
import {subjectsTable} from '@Entity/Subject';
import {encountersTable} from '@Entity/Encounter';
import {transcriptionSegmentsTable} from '@Entity/TranscriptionSegment';

/**
 * Database Class
 * Manages database connection, schema, and initialization
 */
export class Database {
    private readonly driver: ReturnType<typeof openDatabaseSync>;
    public readonly schema: Record<string, SQLiteTable>;
    public readonly db: ExpoSQLiteDatabase<Record<string, SQLiteTable>>;
    private isInitialized = false;

    constructor() {
        // Build schema object from all entities
        // Collects exported table schemas from Entity files
        this.schema = {
            queue_items: queueItemsTable,
            therapists: therapistsTable,
            subjects: subjectsTable,
            encounters: encountersTable,
            transcription_segments: transcriptionSegmentsTable,
        };

        this.driver = openDatabaseSync('tiro_scribe.db', {
            enableChangeListener: true,
            enableCRSQLite: false,
        });
        this.db = drizzle(this.driver, {schema: this.schema});
    }

    /**
     * Initialize database
     * Applies Drizzle migrations to create/update tables
     * Migrations are generated from schema using: pnpm db:migrate:generate
     */
    async initialize(): Promise<void> {
        if (this.isInitialized) {
            return;
        }

        let migrations: {default: {journal: unknown; migrations: Record<string, string>}} | {journal: unknown; migrations: Record<string, string>};
        try {
            // Import migrations - will fail if file doesn't exist
            // Use require() for Jest compatibility, fallback to dynamic import for production
            // @ts-expect-error - migrations.js is generated by drizzle-kit and has dynamic structure
            let migrationsModule;
            try {
                // Try require first (works in Jest/Node.js)
                migrationsModule = require('../../drizzle/migrations');
            } catch {
                // Fallback to dynamic import (works in React Native/Expo)
                migrationsModule = await import('../../drizzle/migrations');
            }
            migrations = migrationsModule.default || migrationsModule;
        } catch (error) {
            // Check if this is a "module not found" error
            const errorWithCode = error as Error & {code?: string};
            const isModuleNotFound = 
                errorWithCode instanceof Error && (
                    errorWithCode.message.includes('Cannot find module') ||
                    errorWithCode.message.includes('MODULE_NOT_FOUND') ||
                    errorWithCode.code === 'MODULE_NOT_FOUND'
                );

            if (isModuleNotFound) {
                throw new Error(
                    '❌ Database migrations not found!\n\n' +
                    'To fix this, run:\n' +
                    '  pnpm db:migrate:generate\n\n' +
                    'This will generate migration files from your Drizzle schema definitions.\n' +
                    'The prebuild script should catch this, but if you see this error,\n' +
                    'it means migrations need to be generated manually.'
                );
            }
            // Re-throw if it's a different error
            throw error;
        }

        try {
            // Apply all pending migrations
            // This will create tables based on the Drizzle schema definitions
            // @ts-expect-error - migrate expects MigrationConfig which matches our structure
            await migrate(this.db, migrations);
        } catch (error) {
            // If migration application fails, provide helpful context
            const errorMessage = error instanceof Error ? error.message : String(error);
            throw new Error(
                `Failed to apply database migrations: ${errorMessage}\n\n` +
                'This usually means:\n' +
                '  - Migration files are corrupted or incompatible\n' +
                '  - Database schema is out of sync\n\n' +
                'Try regenerating migrations with: pnpm db:migrate:generate'
            );
        }

        this.isInitialized = true;
    }

    /**
     * Ensure database is initialized
     * Creates tables if they don't exist
     */
    async ensureInitialized(): Promise<void> {
        await this.initialize();
    }
}

/**
 * Singleton database instance
 */
const databaseService = new Database();

/**
 * Export database client for use in services and components
 * Usage:
 * 
 * import {database} from '@Service/Database';
 * import {queueItemsTable} from '@Entity/QueueItem';
 * import {eq} from 'drizzle-orm';
 * 
 * // Query
 * const items = await database.select().from(queueItemsTable).where(eq(queueItemsTable.status, 'pending'));
 * 
 * // Insert
 * await database.insert(queueItemsTable).values({...});
 * 
 * // Update
 * await database.update(queueItemsTable).set({status: 'processing'}).where(eq(queueItemsTable.id, '123'));
 */
export const database = databaseService.db;
export const db = databaseService.db;

/**
 * Initialize database on app startup
 * Creates tables if they don't exist
 */
export async function ensureDatabaseInitialized(): Promise<void> {
    await databaseService.ensureInitialized();
}

/**
 * Export schema for use in queries
 */
export const schema = databaseService.schema;

/**
 * Export individual table references
 */
export {queueItemsTable} from '@Entity/QueueItem';
export {therapistsTable} from '@Entity/Therapist';
export {subjectsTable} from '@Entity/Subject';
export {encountersTable} from '@Entity/Encounter';
export {transcriptionSegmentsTable} from '@Entity/TranscriptionSegment';

/**
 * Type exports for use in application code
 */
export type {QueueItemSchema, NewQueueItemSchema} from '@Entity/QueueItem';
export type {TherapistSchema, NewTherapistSchema} from '@Entity/Therapist';
export type {SubjectSchema, NewSubjectSchema} from '@Entity/Subject';
export type {EncounterSchema, NewEncounterSchema} from '@Entity/Encounter';
export type {TranscriptionSegmentSchema, NewTranscriptionSegmentSchema} from '@Entity/TranscriptionSegment';
