/** @type {import('@hey-api/openapi-ts').UserConfig} */
export default {
    input: './src/Api/spec.yaml',
    output: {
        path: 'src/Api/generated',
        fileName: {
            case: 'PascalCase',
            suffix: null,
        },
        header: [
            '/* eslint-disable */',
            '// Generated by @hey-api/openapi-ts. Exempt from project MDC. Do not edit.',
        ],
        preferExportAll: true,
        postProcess: ['biome:format'],
    },
    types: {
        name: 'PascalCase',
    },
    plugins: ['@hey-api/client-fetch'],
};
