/**
 * Therapist Entity
 * Schema and entity class defined in the same file
 * 
 * IMPORTANT: The projection_key is NEVER stored in the database or anywhere else.
 * It is ONLY generated in memory from the therapist's password when they log in.
 * Once the session ends, the projection key is destroyed and can only be
 * regenerated by the therapist using their password.
 */

import {sqliteTable, text, integer, index} from 'drizzle-orm/sqlite-core';
import CryptoJS from 'crypto-js';
import {AbstractEntity} from './AbstractEntity';

/**
 * Therapists Table Schema
 * Therapist accounts and authentication
 */
export const therapistsTable = sqliteTable(
    'therapists',
    {
        id: text('id').primaryKey(),
        uuid: text('uuid').notNull().unique(),
        passwordHash: text('password_hash').notNull(),
        name: text('name'),
        createdAt: integer('created_at', {mode: 'timestamp_ms'}).notNull(),
        updatedAt: integer('updated_at', {mode: 'timestamp_ms'}).notNull(),
    },
    table => ({
        uuidIdx: index('therapists_uuid_idx').on(table.uuid),
    })
);

export type TherapistSchema = typeof therapistsTable.$inferSelect;
export type NewTherapistSchema = typeof therapistsTable.$inferInsert;

/**
 * Therapist Entity Class
 * Provides business logic and helper methods for therapist records
 */
export class Therapist extends AbstractEntity<TherapistSchema> {
    public readonly id: string;
    public readonly uuid: string;
    public readonly passwordHash: string;
    public readonly name: string | null;
    public readonly createdAt: Date;
    public readonly updatedAt: Date;

    constructor(data: TherapistSchema) {
        super(data);
        this.id = data.id;
        this.uuid = data.uuid;
        this.passwordHash = data.passwordHash;
        this.name = data.name;
        this.createdAt = new Date(data.createdAt);
        this.updatedAt = new Date(data.updatedAt);
    }

    /**
     * Get projection key derived from therapist's password
     * 
     * IMPORTANT: This key is generated in memory only and NEVER stored.
     * It can only be generated by providing the therapist's password.
     * The key exists only during the method call and is not persisted.
     * 
     * @param password - Therapist password (required to generate the key)
     * @returns Derived projection key (exists only in memory)
     */
    public getProjectionKey(password: string): string {
        // Use PBKDF2 to derive key from UUID + password
        // This ensures deterministic key generation that requires the password
        // The key is NEVER stored - only exists in memory during the method call
        const salt = `therapist_projection_${this.uuid}`;
        return CryptoJS.PBKDF2(password, salt, {
            keySize: 512 / 32, // 512 bits = 16 words
            iterations: 10000,
        }).toString();
    }

}
