/**
 * Therapist Model
 * WatermelonDB model for therapist information
 * 
 * IMPORTANT: The projection_key is NEVER stored in the database or anywhere else.
 * It is ONLY generated in memory from the therapist's password when they log in.
 * Once the session ends, the projection key is destroyed and can only be
 * regenerated by the therapist using their password.
 */

import {field, date} from '@nozbe/watermelondb/decorators';
import type {TableSchemaSpec} from '@nozbe/watermelondb/Schema';
import {AbstractModel} from './AbstractModel';
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import CryptoJS from 'crypto-js';

dayjs.extend(utc);

/**
 * Therapist Model Class
 * Defines both schema specification and model fields in one class
 */
export class Therapist extends AbstractModel {
    /**
     * Database table name (static property)
     */
    public static readonly tableName = 'therapists';

    /**
     * Schema specification (static property)
     * 
     * NOTE: projection_key is NEVER stored in the database.
     * It is derived from password in memory only when therapist logs in.
     */
    public static readonly schemaSpec: TableSchemaSpec = {
        name: 'therapists',
        columns: [
            {name: 'uuid', type: 'string' as const, isIndexed: true},
            {name: 'password_hash', type: 'string' as const},
            {name: 'name', type: 'string' as const, isOptional: true},
            {name: 'created_at', type: 'number' as const},
            {name: 'updated_at', type: 'number' as const},
        ],
    };

    @field('uuid')
    public uuid: string = '';

    /**
     * Password hash (never store plain password)
     * Used for authentication only.
     * The projection_key is derived from password in memory, never stored.
     */
    @field('password_hash')
    public passwordHash: string = '';

    @field('name')
    public name: string | null = null;

    @date('created_at')
    public createdAt: Date = dayjs.utc().toDate();

    @date('updated_at')
    public updatedAt: Date = dayjs.utc().toDate();

    /**
     * Get projection key derived from therapist's password
     * 
     * IMPORTANT: This key is generated in memory only and NEVER stored.
     * It can only be generated by providing the therapist's password.
     * The key exists only during the method call and is not persisted.
     * 
     * @param password - Therapist password (required to generate the key)
     * @returns Derived projection key (exists only in memory)
     */
    public getProjectionKey(password: string): string {
        // Use PBKDF2 to derive key from UUID + password
        // This ensures deterministic key generation that requires the password
        // The key is NEVER stored - only exists in memory during the method call
        const salt = `therapist_projection_${this.uuid}`;
        return CryptoJS.PBKDF2(password, salt, {
            keySize: 512 / 32, // 512 bits = 16 words
            iterations: 10000,
        }).toString();
    }
}
