/**
 * Custom Expo config plugin for onnxruntime-react-native.
 *
 * The official app.plugin.js only adds a build.gradle dependency but does NOT:
 *   1. Add the project to settings.gradle (so Gradle can't resolve it)
 *   2. Register OnnxruntimePackage with React Native (so JS can't find the native module)
 *
 * This plugin fixes both issues and survives `npx expo prebuild --clean`.
 *
 * Usage in app.json:
 *   "plugins": [
 *     "./plugins/withOnnxruntime",
 *     "onnxruntime-react-native"
 *   ]
 *
 * Place this file at: <project-root>/plugins/withOnnxruntime.js
 */
const {
    withSettingsGradle,
    withMainApplication,
    createRunOncePlugin,
} = require('expo/config-plugins');

const PLUGIN_NAME = 'withOnnxruntime';
const SETTINGS_TAG = 'onnxruntime-react-native';

/**
 * 1. Add onnxruntime-react-native as a Gradle project in settings.gradle.
 *    Without this, `implementation project(':onnxruntime-react-native')` in
 *    build.gradle is a dangling reference and the native code never compiles.
 */
function withOnnxruntimeSettings(config) {
    return withSettingsGradle(config, (cfg) => {
        const contents = cfg.modResults.contents;

        // Don't add twice
        if (contents.includes(`:${SETTINGS_TAG}`)) {
            return cfg;
        }

        // Resolve the real path through pnpm/node_modules symlinks.
        // At prebuild time, node can resolve the package location.
        const settingsEntry = [
            '',
            `// ${SETTINGS_TAG} @generated by ${PLUGIN_NAME}`,
            `include ':${SETTINGS_TAG}'`,
            `project(':${SETTINGS_TAG}').projectDir = new File(`,
            `  providers.exec {`,
            `    workingDir(rootDir)`,
            `    commandLine("node", "--print", "require.resolve('onnxruntime-react-native/android/build.gradle', { paths: [require.resolve('react-native/package.json')] })")`,
            `  }.standardOutput.asText.get().trim()`,
            `).getParentFile()`,
            `// ${SETTINGS_TAG} @end`,
        ].join('\n');

        cfg.modResults.contents = contents + settingsEntry;
        return cfg;
    });
}

/**
 * 2. Register OnnxruntimePackage in MainApplication.
 *    The package uses the old ReactPackage interface. Expo's autolinking
 *    doesn't pick it up because there's no react-native.config.js or
 *    expo-module.config.json in the npm package.
 */
function withOnnxruntimePackage(config) {
    return withMainApplication(config, (cfg) => {
        const contents = cfg.modResults.contents;

        // Don't add twice
        if (contents.includes('OnnxruntimePackage')) {
            return cfg;
        }

        // Add import
        const importLine = 'import ai.onnxruntime.reactnative.OnnxruntimePackage;';
        if (!contents.includes(importLine)) {
            // Insert after the last import statement
            const lastImportIndex = contents.lastIndexOf('import ');
            const endOfLastImport = contents.indexOf('\n', lastImportIndex);
            cfg.modResults.contents =
                contents.slice(0, endOfLastImport + 1) +
                importLine +
                '\n' +
                contents.slice(endOfLastImport + 1);
        }

        // Add package to getPackages()
        // Look for the packages list in the ReactNativeHost or DefaultReactNativeHost
        let updated = cfg.modResults.contents;

        // Pattern 1: Kotlin-style with PackageList (Expo SDK 54+)
        // Looks for: packages.add(...)  or  return PackageList(this).packages
        if (updated.includes('PackageList(this).packages')) {
            // Add after PackageList line
            updated = updated.replace(
                /(PackageList\(this\)\.packages)/,
                '$1.apply { add(OnnxruntimePackage()) }'
            );
            cfg.modResults.contents = updated;
        }
        // Pattern 2: Java-style getPackages method
        else if (updated.includes('getPackages()')) {
            updated = updated.replace(
                /(packages\.add\(new\s+\w+\(\)\);)/,
                '$1\n              packages.add(new OnnxruntimePackage());'
            );
            cfg.modResults.contents = updated;
        }

        return cfg;
    });
}

/**
 * Compose both modifications.
 */
function withOnnxruntime(config) {
    config = withOnnxruntimeSettings(config);
    config = withOnnxruntimePackage(config);
    return config;
}

module.exports = createRunOncePlugin(withOnnxruntime, PLUGIN_NAME, '1.0.0');
