const {
    withSettingsGradle,
    withMainApplication,
    withDangerousMod,
    createRunOncePlugin,
} = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

const PLUGIN_NAME = 'withOnnxruntime';
const SETTINGS_TAG = 'onnxruntime-react-native';

const ORT_PODSPEC_MARKER =
    "'HEADER_SEARCH_PATHS' => '\"${PODS_ROOT}/Headers/Public/onnxruntime-extensions-c\"";

/**
 * 1. Patch the onnxruntime-react-native podspec to include the header search
 *    path for onnxruntime-extensions-c. Without this, SessionUtils.cpp fails
 *    to find <onnxruntime_extensions.h> when ORT_ENABLE_EXTENSIONS is set.
 */
function withOnnxruntimePodspecHeaderFix(config) {
    return withDangerousMod(config, [
        'ios',
        async (cfg) => {
            const podspecPath = findOrtPodspec(cfg.modRequest.platformProjectRoot);
            if (!podspecPath) {
                return cfg;
            }

            let contents = fs.readFileSync(podspecPath, 'utf-8');

            if (contents.includes(ORT_PODSPEC_MARKER)) {
                return cfg;
            }

            const headerPaths = '"${PODS_ROOT}/Headers/Public/onnxruntime-extensions-c" "${PODS_ROOT}/Headers/Private/onnxruntime-extensions-c" "${PODS_ROOT}/onnxruntime-extensions-c/Headers"';
            contents = contents.replace(
                /('OTHER_CPLUSPLUSFLAGS' => common_cpp_flags \+ ' -DORT_ENABLE_EXTENSIONS=1',)/,
                "'HEADER_SEARCH_PATHS' => '" + headerPaths + "',\n        $1"
            );

            fs.writeFileSync(podspecPath, contents, 'utf-8');
            return cfg;
        },
    ]);
}

/**
 * Resolve the onnxruntime-react-native podspec through pnpm symlinks.
 */
function findOrtPodspec(iosRoot) {
    const candidates = [
        path.join(iosRoot, '..', 'node_modules', 'onnxruntime-react-native', 'onnxruntime-react-native.podspec'),
    ];

    const localPodspec = path.join(
        iosRoot,
        'Pods',
        'Local Podspecs',
        'onnxruntime-react-native.podspec.json'
    );
    if (fs.existsSync(localPodspec)) {
        const json = JSON.parse(fs.readFileSync(localPodspec, 'utf-8'));
        const source = json.source;
        if (source && source.path) {
            candidates.unshift(path.join(iosRoot, 'Pods', 'Local Podspecs', source.path));
        }
    }

    for (const candidate of candidates) {
        if (fs.existsSync(candidate)) {
            return candidate;
        }
    }

    return null;
}

/**
 * 2. Add onnxruntime-react-native as a Gradle project in settings.gradle.
 */
function withOnnxruntimeSettings(config) {
    return withSettingsGradle(config, (cfg) => {
        const contents = cfg.modResults.contents;

        if (contents.includes(`:${SETTINGS_TAG}`)) {
            return cfg;
        }

        const settingsEntry = [
            '',
            `// ${SETTINGS_TAG} @generated by ${PLUGIN_NAME}`,
            `include ':${SETTINGS_TAG}'`,
            `project(':${SETTINGS_TAG}').projectDir = new File(`,
            `  providers.exec {`,
            `    workingDir(rootDir)`,
            `    commandLine("node", "--print", "require.resolve('onnxruntime-react-native/android/build.gradle', { paths: [require.resolve('react-native/package.json')] })")`,
            `  }.standardOutput.asText.get().trim()`,
            `).getParentFile()`,
            `// ${SETTINGS_TAG} @end`,
        ].join('\n');

        cfg.modResults.contents = contents + settingsEntry;
        return cfg;
    });
}

/**
 * 3. Register OnnxruntimePackage in MainApplication.
 */
function withOnnxruntimePackage(config) {
    return withMainApplication(config, (cfg) => {
        const contents = cfg.modResults.contents;

        if (contents.includes('OnnxruntimePackage')) {
            return cfg;
        }

        const importLine = 'import ai.onnxruntime.reactnative.OnnxruntimePackage;';
        if (!contents.includes(importLine)) {
            const lastImportIndex = contents.lastIndexOf('import ');
            const endOfLastImport = contents.indexOf('\n', lastImportIndex);
            cfg.modResults.contents =
                contents.slice(0, endOfLastImport + 1) +
                importLine +
                '\n' +
                contents.slice(endOfLastImport + 1);
        }

        let updated = cfg.modResults.contents;

        if (updated.includes('PackageList(this).packages')) {
            updated = updated.replace(
                /(PackageList\(this\)\.packages)/,
                '$1.apply { add(OnnxruntimePackage()) }'
            );
            cfg.modResults.contents = updated;
        } else if (updated.includes('getPackages()')) {
            updated = updated.replace(
                /(packages\.add\(new\s+\w+\(\)\);)/,
                '$1\n              packages.add(new OnnxruntimePackage());'
            );
            cfg.modResults.contents = updated;
        }

        return cfg;
    });
}

/**
 * 4. Fix ONNX Android C++ compilation and TurboModule binding issues.
 * Bypasses PNPM path hash issues with Prefab.
 */
function withOnnxruntimeAndroidFix(config) {
    return withDangerousMod(config, [
        'android',
        async (cfg) => {
            const pkgPath = path.join(cfg.modRequest.projectRoot, 'node_modules', 'onnxruntime-react-native');

            // Fix Gradle VersionNumber bug
            const gradlePath = path.join(pkgPath, 'android', 'build.gradle');
            if (fs.existsSync(gradlePath)) {
                let content = fs.readFileSync(gradlePath, 'utf8');
                content = content.replace(/if\s*\(\s*VersionNumber\.parse\(REACT_NATIVE_VERSION\)[\s\S]*?fbjni:\+"\r?\n\s*\}/m, '// Legacy fbjni extraction removed by Expo Plugin');
                fs.writeFileSync(gradlePath, content);
            }

            // Fix JS TurboModule Binding
            const bindingJsPath = path.join(pkgPath, 'lib', 'binding.js');
            if (fs.existsSync(bindingJsPath)) {
                let content = fs.readFileSync(bindingJsPath, 'utf8');
                content = content.replace(/exports\.Module = react_native_1\.NativeModules\.Onnxruntime;/g, "exports.Module = react_native_1.NativeModules.Onnxruntime ?? require('react-native').TurboModuleRegistry.get('Onnxruntime');");
                fs.writeFileSync(bindingJsPath, content);
            }

            // Fix TS TurboModule Binding (for consistency)
            const bindingTsPath = path.join(pkgPath, 'lib', 'binding.ts');
            if (fs.existsSync(bindingTsPath)) {
                let content = fs.readFileSync(bindingTsPath, 'utf8');
                content = content.replace(/export const Module = NativeModules\.Onnxruntime;/g, "export const Module = NativeModules.Onnxruntime ?? TurboModuleRegistry.get('Onnxruntime');");
                content = content.replace(/import \{ NativeModules \} from 'react-native';/, "import { NativeModules, TurboModuleRegistry } from 'react-native';");
                fs.writeFileSync(bindingTsPath, content);
            }

            return cfg;
        },
    ]);
}

function withOnnxruntime(config) {
    config = withOnnxruntimePodspecHeaderFix(config);
    config = withOnnxruntimeSettings(config);
    config = withOnnxruntimePackage(config);
    config = withOnnxruntimeAndroidFix(config);
    return config;
}

module.exports = createRunOncePlugin(withOnnxruntime, PLUGIN_NAME, '1.0.0');
