/**
 * Repository: Generic CRUD over SQLite via Kysely (query builder) and expo-sqlite (execution).
 * All SQL is generated by Kysely. Hybrid storage: uuid (primary key), data (JSON), plus real foreign key columns.
 * Direct-to-Kysely implementation without EntityGateway or RowMapper intermediate layers.
 * Updated: Added generic TEntity parameter
 */

import { CompiledQuery, type Kysely } from 'kysely';
import { Container } from '../Container';
import type { MetadataConstructor } from '../Decorator/Type';
import { DatabaseException } from '../Exception';
import { AppLogger } from '../Service/Logger';
import type { AbstractEntity } from './AbstractEntity';
import { Collection } from './Collection';
import { Criteria } from './Criteria';
import { EntityMetadata } from './Decorator';
import { QueryBuilder } from './QueryBuilder';
import { QueryCompiler, type QueryOptions } from './QueryCompiler';
import type { DatabaseSchema, EntityClass } from './Type';

/**
 * Shape of an entity class construc
 * Every concrete entity extends AbstractEntity (and therefore implements
 * the Entity interface); the constructor a Entity object and
 * returns an Entity instance.  Declaring the interface here lets callers use
 * `Entity` rather than rely on the concrete class type.
 */

/** Foreign key column reference (property name → column name). */
interface RealForeignKeyColumn {
    propertyName: string;
    columnName: string;
}

export class Repository<TEntity extends AbstractEntity = AbstractEntity> {
    private readonly allowedKeys: ReadonlySet<string>;
    private readonly db: Kysely<DatabaseSchema>;
    private readonly entityClass: EntityClass<TEntity>;
    private readonly metadata: EntityMetadata;
    private readonly primaryKeyField: string;
    private readonly queryCompiler: QueryCompiler;
    private readonly realForeignKeyColumns: RealForeignKeyColumn[];
    private readonly tableName: string;

    // static helpers (e.g. create) are declared below after constructor to follow ordering rules

    protected constructor(entityClass: EntityClass<TEntity>, tableName: string, db?: Kysely<DatabaseSchema>) {
        this.entityClass = entityClass;
        this.tableName = tableName;
        this.db = db ?? Container.get(QueryBuilder);
        this.metadata = EntityMetadata.for(entityClass as MetadataConstructor);
        this.primaryKeyField = this.metadata.getPrimaryKeyField();
        this.realForeignKeyColumns = this.metadata.getForeignKeyColumns() as RealForeignKeyColumn[];
        // Every property that can be used in Criteria (for findBy/where
        // clauses) must appear in this set.  We derive the list from column
        // metadata, which usually includes the primary key, but there are
        // edge cases where metadata omits it.  To be safe we always call
        // `add` – the Set makes the operation idempotent, so if the key was
        // already present this is a no-op.
        const columnNames = this.metadata.getColumnNames();
        const allowedKeys = new Set(columnNames);
        allowedKeys.add(this.primaryKeyField); // idempotent guarantee
        this.allowedKeys = allowedKeys;
        this.queryCompiler = new QueryCompiler(this.tableName, this.metadata);
    }

    /**
     * Creates the appropriate repository: custom repo class when provided (e.g. by Registry), else generic Repository.
     */
    public static create<TEntity extends AbstractEntity>(
        entityName: string,
        EntityClass: EntityClass<TEntity>,
        customRepositoryClass?: new () => Repository<TEntity>,
    ): Repository<TEntity> {
        if (customRepositoryClass) {
            return new customRepositoryClass();
        }

        // the provided class already matches the EntityClass constructor signature
        return new Repository<TEntity>(EntityClass, entityName);
    }

    /**
     * Check if an entity with the given primary key exists.
     */
    public async exists(primaryKey: string): Promise<boolean> {
        const compiled = this.queryCompiler.compileExists({ [this.primaryKeyField]: primaryKey });
        const rows = await this.executeQuery(compiled);
        return rows.length > 0;
    }

    /**
     * Find entity by primary key.
     */
    public async find(primaryKey: string): Promise<TEntity | null> {
        return this.findOneBy(Criteria.of({ [this.primaryKeyField]: primaryKey }));
    }

    /**
     * Find all entities (no criteria).
     */
    public async findAll(options?: QueryOptions): Promise<Collection<TEntity>> {
        return this.findBy(Criteria.of({}), options);
    }

    /**
     * Find entities matching criteria.
     */
    public async findBy(criteria: Criteria, options?: QueryOptions): Promise<Collection<TEntity>> {
        // Validate criteria keys against allowed entity properties
        criteria.validate(this.allowedKeys);

        const compiled = this.queryCompiler.build(criteria.value(), options);
        const rows = await this.executeQuery(compiled);
        const entities = this.toEntities(rows);
        return new Collection(entities);
    }

    /**
     * Find a single entity matching criteria, or null if none.
     */
    public async findOneBy(criteria: Criteria, options?: QueryOptions): Promise<TEntity | null> {
        const compiled = this.queryCompiler.build(criteria.value(), { ...options, limit: 1 });
        const rows = await this.executeQuery(compiled);
        return rows.length > 0 ? this.toEntity(rows[0]) : null;
    }

    /**
     * Persist: create if entity unknown (primary key not in table), else update.
     * Uses Kysely's onConflict for upsert operation.
     * Real foreign key columns are written so REFERENCES constraints are satisfied.
     */
    public async persist(entity: TEntity): Promise<TEntity> {
        const logger = AppLogger.getInstance();
        const primaryKey = entity.primaryKey;

        // Validate primary key is not empty or whitespace-only
        if (!primaryKey || primaryKey.trim().length === 0) {
            throw new DatabaseException(
                'Cannot persist entity with empty or whitespace-only primary key.',
                'REPOSITORY_INVALID_PRIMARY_KEY',
                undefined,
                {
                    tableName: this.tableName,
                    primaryKey,
                },
            );
        }

        const data = entity.toPlainObject();
        logger.debug('[Repository] persist:', { primaryKey, dataKeys: Object.keys(data) });

        // Check if entity exists to determine if we need to merge with stored record
        const exists = await this.exists(primaryKey);
        let mergedWithStored: Record<string, unknown>;

        if (exists) {
            // Update: load stored record, merge with incoming data
            const stored = await this.find(primaryKey);
            if (stored == null) {
                throw new DatabaseException(
                    `Cannot update: entity ${primaryKey} disappeared between exists() and find().`,
                    'REPOSITORY_CONCURRENT_MODIFICATION',
                    undefined,
                    { tableName: this.tableName, primaryKey },
                );
            }
            const storedRecord = stored.toPlainObject();
            mergedWithStored = this.mergeForPersist(data, storedRecord);
        } else {
            // Create: merge with defaults only
            mergedWithStored = this.mergeForPersist(data);
        }

        const row = this.toRow(mergedWithStored);

        // Upsert using Kysely's onConflict
        await this.db
            .insertInto(this.tableName as keyof DatabaseSchema)
            // biome-ignore lint/suspicious/noExplicitAny: Dynamic table insertion requires type assertion
            .values(row as any)
            .onConflict((oc) => oc.column('uuid').doUpdateSet(row))
            .execute();

        return this.refresh(entity);
    }

    /**
     * Reloads an entity from the database by its primary key. Throws if not found.
     */
    public async refresh(entity: TEntity): Promise<TEntity> {
        const primaryKey = entity.primaryKey;
        const loaded = await this.find(primaryKey);
        if (loaded == null) {
            throw new DatabaseException(
                `Cannot refresh: no entity with primary key "${primaryKey}" in table "${this.tableName}".`,
                'REPOSITORY_ENTITY_NOT_FOUND',
                undefined,
                { tableName: this.tableName, primaryKey },
            );
        }

        return loaded;
    }

    public async remove(entity: TEntity): Promise<void> {
        await this.db
            .deleteFrom(this.tableName as keyof DatabaseSchema)
            .where('uuid', '=', entity.primaryKey)
            .execute();
    }

    /**
     * Full-text search (requires FTS table: {tableName}_fts).
     */
    public async search(query: string, options?: QueryOptions): Promise<Collection<TEntity>> {
        const ftsTableName = `${this.tableName}_fts`;
        const compiled = this.queryCompiler.build({}, options);
        // Replace FROM clause to use FTS table instead of main table
        const ftsSql = compiled.sql.replace(`FROM "${this.tableName}"`, `FROM "${ftsTableName}"`);
        // Add MATCH clause
        const matchClause = `"${ftsTableName}" MATCH ?`;
        const wherePos = ftsSql.toUpperCase().indexOf(' WHERE ');
        let finalSql: string;
        let parameters: unknown[];
        if (wherePos === -1) {
            finalSql = `${ftsSql} WHERE ${matchClause}`;
            parameters = [...compiled.parameters, query];
        } else {
            const beforeWhere = ftsSql.substring(0, wherePos);
            const afterWhere = ftsSql.substring(wherePos + 7); // +7 for " WHERE "
            finalSql = `${beforeWhere} WHERE ${matchClause} AND ${afterWhere}`;
            parameters = [query, ...compiled.parameters];
        }

        try {
            const rows = await this.executeQuery({ sql: finalSql, parameters });
            const entities = this.toEntities(rows);

            return new Collection(entities);
        } catch {
            return new Collection<TEntity>([]);
        }
    }

    /**
     * Runs multiple operations in a single database transaction.
     * All persist, remove, etc. inside the callback use the same transaction; commit on success.
     * Rollback on throw is driver-dependent. Use for bulk writes or when several operations must succeed together.
     * The repo passed to the callback is a base Repository (same entity/table);
     * subclass methods (e.g. TherapistRepository) are not available on it.
     */
    public async transaction<T>(fn: (repo: Repository<TEntity>) => Promise<T>): Promise<T> {
        // If we're already in a transaction, we can't start a new one
        // For simplicity, we'll just execute the callback with the current repository
        if ('isTransaction' in this.db) {
            return await fn(this);
        }

        return await (this.db as Kysely<DatabaseSchema>).transaction().execute(async (trx) => {
            const txRepo = new Repository<TEntity>(this.entityClass, this.tableName, trx);
            return await fn(txRepo);
        });
    }

    // --- private helpers ---------------------------------------------------

    /**
     * Execute a compiled SQL statement using Kysely.
     */
    private async executeQuery(compiled: { sql: string; parameters: unknown[] }): Promise<Record<string, unknown>[]> {
        const result = await this.db.executeQuery(CompiledQuery.raw(compiled.sql, compiled.parameters));

        return (result.rows ?? []) as Record<string, unknown>[];
    }

    /**
     * Merge entity defaults with partial data (and optionally stored record for update).
     * Create: mergeForPersist(data). Update: mergeForPersist(data, storedRecord).
     */
    private mergeForPersist(
        data: Partial<Record<string, unknown>>,
        storedRecord?: Record<string, unknown>,
    ): Record<string, unknown> {
        const logger = AppLogger.getInstance();
        const defaults = this.metadata.getColumnDefaults();

        logger.debug('[Repository] mergeForPersist:', {
            dataKeys: Object.keys(data),
            storedRecordKeys: storedRecord ? Object.keys(storedRecord) : undefined,
            defaultsKeys: Object.keys(defaults),
            hasStoredRecord: !!storedRecord,
        });

        const merged: Record<string, unknown> = { ...defaults };
        // Apply stored record first (for updates)
        if (storedRecord != null) {
            for (const [key, value] of Object.entries(storedRecord)) {
                if (value !== undefined) {
                    merged[key] = value;
                }
            }
        }
        // Then apply incoming data (overwrites stored values)
        for (const [key, value] of Object.entries(data)) {
            if (value !== undefined) {
                merged[key] = value;
            }
        }

        logger.debug('[Repository] mergeForPersist result keys:', Object.keys(merged));
        return merged;
    }

    /**
     * Normalize data for writing to JSON column.
     * Filters out non-column properties and ensures values are serializable.
     */
    private normalizeForWrite(data: Record<string, unknown>): Record<string, unknown> {
        const normalized: Record<string, unknown> = {};
        const columnNames = this.metadata.getColumnNames();

        for (const [key, value] of Object.entries(data)) {
            if (columnNames.includes(key)) {
                normalized[key] = value;
            }
        }

        return normalized;
    }

    /**
     * Convert multiple database rows to entities.
     */
    private toEntities(rows: Record<string, unknown>[]): TEntity[] {
        return rows.map((row) => this.toEntity(row));
    }

    /**
     * Convert database row to entity instance.
     */
    private toEntity(row: Record<string, unknown>): TEntity {
        // Parse JSON data
        const data = typeof row.data === 'string' ? JSON.parse(row.data) : row.data;

        // Merge foreign key values back into data
        for (const fk of this.realForeignKeyColumns) {
            if (row[fk.columnName] !== undefined && row[fk.columnName] !== null) {
                data[fk.propertyName] = row[fk.columnName];
            }
        }

        // Create entity instance
        const entity = new this.entityClass(data);

        // Ensure primary key is set (should already be in data from row.uuid)
        if (entity.primaryKey !== row.uuid) {
            (entity as unknown as Record<string, unknown>)[this.primaryKeyField] = row.uuid;
        }

        return entity;
    }

    /**
     * Convert plain data to database row format (uuid, data JSON, plus foreign key columns).
     */
    private toRow(data: Record<string, unknown>): Record<string, unknown> {
        const row: Record<string, unknown> = {
            uuid: data[this.primaryKeyField],
            data: JSON.stringify(this.normalizeForWrite(data)),
        };

        // Add real foreign key columns
        for (const fk of this.realForeignKeyColumns) {
            const value = data[fk.propertyName];
            row[fk.columnName] = value == null ? null : String(value as string | number | boolean);
        }

        return row;
    }
}
