/**
 * Repository: Generic CRUD over SQLite via Kysely (query builder) and op-sqlite (execution).
 * All SQL is generated by Kysely. Hybrid storage: uuid (primary key), data (JSON), plus real foreign key columns.
 * Read operations (find, findBy, findAll, search) and orchestration (persist, refresh, transaction) live here;
 * write/delete SQL is delegated to EntityGateway (persist, remove).
 */

import type { DB, Transaction } from '@op-engineering/op-sqlite';
import { sql } from 'kysely';
import snakeCase from 'lodash/snakeCase';
import type { MetadataConstructor } from '../Decorator/Type';
import { DatabaseException } from '../Exception';
import type { AbstractEntity, EntityClassStatic, EntityConstructorInput } from './AbstractEntity';
import { Criteria } from './Criteria';
import { Database } from './Database';
import { EntityMetadata } from './Decorator';
import { EntityGateway } from './EntityGateway';
import { type QueryOptions, QueryCompiler } from './QueryCompiler';
import { RecordNormalizer } from './RecordNormalizer';
import { type RealForeignKeyColumn, RowMapper } from './RowMapper';
import { qb } from './Kysely';

/** Entity constructor signature (plain data in, entity out). */
type EntityConstructor<TEntity extends AbstractEntity> = new (data?: EntityConstructorInput) => TEntity;

/** Entity class shape accepted by Repository.create (constructor + entityName). */
type EntityClassForCreate<TEntity extends AbstractEntity> = EntityConstructor<TEntity> & {
    entityName: string;
};

export class Repository<TEntity extends AbstractEntity> {
    private readonly entityClass: EntityConstructor<TEntity>;
    private readonly tableName: string;
    private readonly metadata: EntityMetadata;
    private readonly primaryKeyField: string;
    private readonly primaryKeyColumnName: string;
    private readonly recordNormalizer: RecordNormalizer;
    private readonly realForeignKeyColumns: RealForeignKeyColumn[];
    private readonly allowedCriteriaKeys: ReadonlySet<string>;
    private readonly entityGateway: EntityGateway;
    private readonly queryCompiler: QueryCompiler;
    private readonly rowMapper: RowMapper<TEntity>;

    /**
     * Creates the appropriate repository: custom repo class when provided (e.g. by Registry), else generic Repository.
     */
    public static create<TEntity extends AbstractEntity>(
        entityName: string,
        EntityClass: EntityClassForCreate<TEntity>,
        customRepositoryClass?: new () => Repository<AbstractEntity>,
    ): Repository<AbstractEntity> {
        if (customRepositoryClass) {
            return new customRepositoryClass();
        }

        return new Repository<TEntity>(EntityClass, entityName, Database.getConnection());
    }

    protected constructor(entityClass: EntityConstructor<TEntity>, tableName: string, connection: DB | Transaction) {
        this.entityClass = entityClass;
        this.tableName = tableName;
        this.metadata = EntityMetadata.for(entityClass as MetadataConstructor);
        this.primaryKeyField = this.metadata.getPrimaryKeyField();
        this.primaryKeyColumnName = snakeCase(this.primaryKeyField);
        this.recordNormalizer = new RecordNormalizer(this.metadata);
        this.realForeignKeyColumns = this.metadata.getForeignKeyColumns();
        this.allowedCriteriaKeys = new Set(this.metadata.getColumnNames());
        this.entityGateway = new EntityGateway(connection, this.tableName, this.primaryKeyColumnName, this.realForeignKeyColumns);
        this.queryCompiler = new QueryCompiler(this.tableName, this.metadata);
        this.rowMapper = new RowMapper(entityClass as EntityClassStatic<TEntity>, this.metadata, this.recordNormalizer);
    }

    /**
     * Merge entity defaults with partial data (and optionally stored record for update).
     * Create: mergeForPersist(data). Update: mergeForPersist(data, storedRecord).
     */
    private mergeForPersist(data: Partial<Record<string, unknown>>, storedRecord?: Record<string, unknown>): Record<string, unknown> {
        const defaults = this.metadata.getColumnDefaults();

        return storedRecord != null ? { ...defaults, ...storedRecord, ...data } : { ...defaults, ...data };
    }

    public async findAll(limit?: number, offset?: number): Promise<TEntity[]> {
        return this.findBy(Criteria.of({}), { limit: limit ?? 1000, offset: offset ?? 0 });
    }

    public async exists(primaryKey: string): Promise<boolean> {
        const stmt = this.queryCompiler.compileExists({ [this.primaryKeyField]: primaryKey });
        const rows = await this.entityGateway.executeQuery(stmt);

        return rows.length > 0;
    }

    public async find(primaryKey: string): Promise<TEntity | null> {
        return this.findOneBy(Criteria.of({ [this.primaryKeyField]: primaryKey }));
    }

    /**
     * All entities where record matches every key in criteria.
     * Use Criteria.of({ ... }) for the criteria argument.
     */
    public async findBy(criteria: Criteria, options?: QueryOptions): Promise<TEntity[]> {
        criteria.validate(this.allowedCriteriaKeys);
        const stmt = this.queryCompiler.build(criteria.value(), options);
        const rows = await this.entityGateway.executeQuery(stmt);
        return this.rowMapper.toEntities(rows);
    }

    /**
     * First entity where record matches every key in criteria, or null.
     * Use Criteria.of({ ... }) for the criteria argument.
     */
    public async findOneBy(criteria: Criteria, options?: QueryOptions): Promise<TEntity | null> {
        criteria.validate(this.allowedCriteriaKeys);
        const stmt = this.queryCompiler.build(criteria.value(), { ...options, limit: 1 });
        const rows = await this.entityGateway.executeQuery(stmt);
        return rows.length > 0 ? this.rowMapper.toEntity(rows[0]) : null;
    }

    /**
     * Persist: create if entity unknown (primary key not in table), else update.
     * Accepts an entity only; serializes via toPlainObject() then delegates to EntityGateway (plain record).
     * Real foreign key columns are written so REFERENCES constraints are satisfied.
     */
    public async persist(entity: TEntity): Promise<TEntity> {
        const data = entity.toPlainObject();
        const merged = this.mergeForPersist(data);
        const primaryKeyValue = merged[this.primaryKeyField] as string;
        if (primaryKeyValue == null || String(primaryKeyValue).trim() === '') {
            throw new DatabaseException(
                `Cannot persist entity with empty primary key in table "${this.tableName}".`,
                'REPOSITORY_EMPTY_PRIMARY_KEY',
                undefined,
                { tableName: this.tableName },
            );
        }
        let mergedWithStored: Record<string, unknown>;
        if (await this.exists(primaryKeyValue)) {
            const existing = await this.find(primaryKeyValue);
            const storedRecord = existing?.toPlainObject() ?? {};
            mergedWithStored = this.mergeForPersist(data, storedRecord);
        } else {
            mergedWithStored = merged;
        }
        const row = this.rowMapper.toRow(mergedWithStored);
        await this.entityGateway.persist(row);

        return this.refresh(entity);
    }

    /**
     * Runs multiple operations in a single database transaction.
     * All persist, remove, etc. inside the callback use the same transaction; commit on success.
     * Rollback on throw is driver-dependent. Use for bulk writes or when several operations must succeed together.
     * The repo passed to the callback is a base Repository (same entity/table);
     * subclass methods (e.g. TherapistRepository) are not available on it.
     */
    public async transaction<T>(fn: (repo: Repository<TEntity>) => Promise<T>): Promise<T> {
        const conn = this.entityGateway.getConnection() as DB;
        const out: { value: T } = { value: undefined as unknown as T };
        await conn.transaction(async (tx: Transaction) => {
            const txRepo = new Repository(this.entityClass, this.tableName, tx as Transaction);
            out.value = await fn(txRepo as Repository<TEntity>);
        });
        return out.value;
    }

    /**
     * Reloads an entity from the database by its primary key. Throws if not found.
     */
    public async refresh(entity: TEntity): Promise<TEntity> {
        const primaryKey = entity.primaryKey;
        const loaded = await this.find(primaryKey);
        if (loaded == null) {
            throw new DatabaseException(
                `Cannot refresh: no entity with primary key "${primaryKey}" in table "${this.tableName}".`,
                'REPOSITORY_ENTITY_NOT_FOUND',
                undefined,
                { tableName: this.tableName, primaryKey },
            );
        }

        return loaded;
    }

    public async remove(entity: TEntity): Promise<void> {
        await this.entityGateway.remove(entity.primaryKey);
    }

    /**
     * Full-text search (requires FTS table: {tableName}_fts).
     * Returns entities whose full-text fields match the query.
     * The search string is bound as a parameter (not concatenated into SQL), so user input is safe from SQL injection.
     */
    public async search(query: string): Promise<TEntity[]> {
        const ftsTableName = `${this.tableName}_fts`;
        const primaryKeyColumn = this.primaryKeyColumnName;
        const selectList = [
            sql.ref(`${this.tableName}.${primaryKeyColumn}`).as(primaryKeyColumn),
            sql.ref(`${this.tableName}.data`).as('data'),
            ...this.realForeignKeyColumns.map((c) => sql.ref(`${this.tableName}.${c.columnName}`).as(c.columnName)),
        ];
        const compiled = sql<Record<string, unknown>[]>`
            SELECT ${sql.join(selectList, sql.raw(', '))}
            FROM ${sql.table(this.tableName)} AS t
            INNER JOIN ${sql.table(ftsTableName)} AS fts
                ON ${sql.ref(`t.${primaryKeyColumn}`)} = ${sql.ref(`fts.${primaryKeyColumn}`)}
            WHERE fts MATCH ${query}
        `.compile(qb);
        const stmt = { sql: compiled.sql, parameters: [...compiled.parameters] };
        const rows = await this.entityGateway.executeQuery(stmt);
        return this.rowMapper.toEntities(rows);
    }

}
