/**
 * Repository: Generic CRUD over SQLite via Kysely (query builder) and op-sqlite (execution).
 * All SQL is generated by Kysely. Hybrid storage: uuid (PK), data (JSON), plus real FK columns.
 */

import isMatch from 'lodash/isMatch';
import { sql } from 'kysely';
import type { MetadataConstructor } from '../Decorator/Type';
import { MetadataReader } from '../Decorator/MetadataReader';
import { DatabaseException } from '../Exception';
import { AbstractEntity, type EntityConstructorInput } from './AbstractEntity';
import type { ColumnOptions } from './Column';
import { Database } from './Database';
import { qb } from './Kysely';
import { EntitySerializer } from './Serializer';

/** Entity class shape accepted by Repository.create (constructor + entityName + optional custom repo). */
type EntityClassForCreate<TEntity extends AbstractEntity> = {
    new (dataOrObservable?: EntityConstructorInput): TEntity;
    entityName: string;
    repositoryClass?: new () => Repository<AbstractEntity>;
};

/** Property and column name for a real FK column (used in INSERT/SELECT). */
interface RealForeignKeyColumn {
    propertyName: string;
    columnName: string;
}

export class Repository<TEntity extends AbstractEntity> {
    private readonly entityClass: new (
        dataOrObservable?: EntityConstructorInput,
    ) => TEntity;
    private readonly tableName: string;
    private readonly primaryKeyField: string;
    private readonly _serializer: EntitySerializer;
    private readonly _realFkColumns: RealForeignKeyColumn[];

    /**
     * Creates the appropriate repository: custom repo if entity defines repositoryClass, else generic Repository.
     */
    public static create<TEntity extends AbstractEntity>(entityName: string, EntityClass: EntityClassForCreate<TEntity>): Repository<AbstractEntity> {
        if (EntityClass.repositoryClass) {
            return new EntityClass.repositoryClass();
        }
        return new Repository<TEntity>(EntityClass, entityName);
    }

    protected constructor(entityClass: new (dataOrObservable?: EntityConstructorInput) => TEntity, tableName: string) {
        this.entityClass = entityClass;
        this.tableName = tableName;
        this.primaryKeyField = AbstractEntity.resolvePrimaryKeyField(entityClass as MetadataConstructor) ?? 'uuid';
        this._serializer = new EntitySerializer(entityClass as new (...args: unknown[]) => AbstractEntity);
        this._realFkColumns = this.buildRealForeignKeyColumns();
    }

    private buildRealForeignKeyColumns(): RealForeignKeyColumn[] {
        return this.getForeignKeyColumnsFromReader(new MetadataReader(this.entityClass as MetadataConstructor));
    }

    /** Uses MetadataReader to find all @ForeignKey-decorated fields and returns property name + snake_case column name. */
    private getForeignKeyColumnsFromReader(reader: MetadataReader): RealForeignKeyColumn[] {
        const columnFields = reader.getFieldsByDecorator('Column');
        const result: RealForeignKeyColumn[] = [];
        for (const field of columnFields) {
            const propertyName = field.getFieldName();
            const decorators = reader.getFieldByProperty(propertyName);
            const hasFk = decorators.some((d) => d.getDecoratorName() === 'ForeignKey');
            if (hasFk) {
                result.push({ propertyName, columnName: this.toSnakeCase(propertyName) });
            }
        }
        return result;
    }

    /** Maps entity plain record to SQL row: uuid, data (JSON), plus snake_case FK columns. */
    private mapToSqlColumns(record: Record<string, unknown>): Record<string, unknown> {
        const pkCol = this.toSnakeCase(this.primaryKeyField);
        const pk = record[this.primaryKeyField];
        const toStore = this._serializer.serialize(record);
        const data = JSON.stringify(toStore);
        const row: Record<string, unknown> = { [pkCol]: pk, data };
        for (const { propertyName, columnName } of this._realFkColumns) {
            row[columnName] = record[propertyName] ?? '';
        }
        return row;
    }

    private async executeQuery(compiled: { sql: string; parameters: readonly unknown[] }): Promise<Record<string, unknown>[]> {
        const db = Database.getConnection();
        type Scalar = string | number | boolean | null;
        const result = await db.execute(compiled.sql, compiled.parameters as Scalar[]);
        const rows = (result as { rows?: unknown[] }).rows;
        return Array.isArray(rows) ? (rows as Record<string, unknown>[]) : [];
    }

    private async executeUpdate(compiled: { sql: string; parameters: readonly unknown[] }): Promise<void> {
        const db = Database.getConnection();
        type Scalar = string | number | boolean | null;
        await db.execute(compiled.sql, compiled.parameters as Scalar[]);
    }

    public async findAll(limit?: number, offset?: number): Promise<TEntity[]> {
        const orderBy = this.getOrderByColumn();
        const limitVal = limit ?? 1000;
        const offsetVal = offset ?? 0;
        const table = this.tableName as keyof import('./Schema').DatabaseSchema;
        const compiled = qb
            .selectFrom(table)
            .selectAll()
            .orderBy(qb.dynamic.ref(orderBy), 'desc')
            .limit(limitVal)
            .offset(offsetVal)
            .compile();
        const rows = await this.executeQuery(compiled);
        return this.hydrateRows(rows);
    }

    public async exists(primaryKey: string): Promise<boolean> {
        const pkCol = this.toSnakeCase(this.primaryKeyField);
        const table = this.tableName as keyof import('./Schema').DatabaseSchema;
        const compiled = qb
            .selectFrom(table)
            .select(sql<number>`1`.as('one'))
            .where(pkCol as 'uuid', '=', primaryKey)
            .limit(1)
            .compile();
        const rows = await this.executeQuery(compiled);
        return rows.length > 0;
    }

    public async find(primaryKey: string): Promise<TEntity | null> {
        const pkCol = this.toSnakeCase(this.primaryKeyField);
        const table = this.tableName as keyof import('./Schema').DatabaseSchema;
        const compiled = qb.selectFrom(table).selectAll().where(pkCol as 'uuid', '=', primaryKey).compile();
        const rows = await this.executeQuery(compiled);
        return rows.length > 0 ? this.hydrateFromRow(rows[0]) : null;
    }

    /** Builds compiled SELECT for scalar criteria (PK, FK, or json_extract). Empty criteria = no WHERE. */
    private buildFindByCompiled(criteria: Record<string, unknown>, limitOne: boolean): { sql: string; parameters: readonly unknown[] } {
        const table = this.tableName as keyof import('./Schema').DatabaseSchema;
        const orderBy = this.getOrderByColumn();
        const keys = Object.keys(criteria);
        let query = qb.selectFrom(table).selectAll();
        for (const key of keys) {
            const value = criteria[key];
            if (key === this.primaryKeyField) {
                query = query.where(this.toSnakeCase(this.primaryKeyField) as 'uuid', '=', value as string);
            } else {
                const fk = this._realFkColumns.find((c) => c.propertyName === key);
                if (fk != null) {
                    query = query.where(fk.columnName as 'uuid', '=', value as string);
                } else {
                    const escapedKey = key.replace(/'/g, "''");
                    query = query.where(sql`json_extract(data, '$.${sql.raw(escapedKey)}')`, '=', value);
                }
            }
        }
        query = query.orderBy(qb.dynamic.ref(orderBy), 'desc');
        if (limitOne) {
            query = query.limit(1);
        }
        return query.compile();
    }

    /** All entities where record matches every key in criteria. Uses SQL WHERE for scalar criteria; in-memory isMatch for nested. */
    public async findBy(criteria: Record<string, unknown>): Promise<TEntity[]> {
        if (this.hasNestedCriteria(criteria)) {
            const allPlain = await this.findAllPlainRecords();
            const matching = allPlain.filter((r) => isMatch(r, criteria));
            return matching.map((r) => new this.entityClass(this._serializer.unserialize(r)));
        }
        if (Object.keys(criteria).length === 0) {
            return this.findAll();
        }
        const compiled = this.buildFindByCompiled(criteria, false);
        const rows = await this.executeQuery(compiled);
        return this.hydrateRows(rows);
    }

    /** First entity where record matches every key in criteria, or null. Uses SQL WHERE for scalar criteria; in-memory for nested. */
    public async findOneBy(criteria: Record<string, unknown>): Promise<TEntity | null> {
        if (this.hasNestedCriteria(criteria)) {
            const allPlain = await this.findAllPlainRecords();
            if (allPlain.length === 0) {
                return null;
            }
            if (Object.keys(criteria).length === 0) {
                return new this.entityClass(this._serializer.unserialize(allPlain[0]));
            }
            const match = allPlain.find((r) => isMatch(r, criteria));
            return match != null ? new this.entityClass(this._serializer.unserialize(match)) : null;
        }
        const compiled = this.buildFindByCompiled(criteria, true);
        const rows = await this.executeQuery(compiled);
        return rows.length > 0 ? this.hydrateFromRow(rows[0]) : null;
    }

    /**
     * Persist: create if entity unknown (pk not in table), else update.
     * Accepts an entity (calls toRecord() internally) or a plain record.
     * Real FK columns are written so REFERENCES constraints are satisfied.
     */
    public async persist(entityOrData: TEntity | Partial<Record<string, unknown>> = {}): Promise<TEntity> {
        const data = entityOrData instanceof AbstractEntity ? (entityOrData as AbstractEntity).toRecord() : entityOrData;
        const merged = this._serializer.mergeWithDefaults(data);
        const pk = merged[this.primaryKeyField] as string;
        if (pk == null || String(pk).trim() === '') {
            throw new DatabaseException(
                `Cannot persist entity with empty primary key in table "${this.tableName}".`,
                'REPOSITORY_EMPTY_PRIMARY_KEY',
                undefined,
                { tableName: this.tableName },
            );
        }
        const exists = await this.exists(pk);
        const mergedWithStored = exists ? this._serializer.mergeWithDefaults(data, await this.getStoredRecord(pk)) : merged;
        const row = this.mapToSqlColumns(mergedWithStored);

        const table = this.tableName as keyof import('./Schema').DatabaseSchema;
        const pkCol = this.toSnakeCase(this.primaryKeyField);
        const compiled = qb
            .insertInto(table)
            .values(row as unknown as import('./Schema').DatabaseSchema[keyof import('./Schema').DatabaseSchema])
            .onConflict((oc) =>
                oc.column(pkCol as 'uuid').doUpdateSet((eb) => {
                    const set: Record<string, unknown> = { data: eb.ref('excluded.data') };
                    for (const { columnName } of this._realFkColumns) {
                        set[columnName] = eb.ref(`excluded.${columnName}` as 'excluded.data');
                    }
                    // doUpdateSet callback return type is inferred as function; set is the update object (excluded refs)
                    // biome-ignore lint/suspicious/noExplicitAny: Kysely doUpdateSet callback return type escape hatch
                    return set as any;
                }),
            )
            .compile();
        await this.executeUpdate(compiled);

        const entity = await this.find(pk);
        if (entity == null) {
            throw new DatabaseException(`Failed to persist entity "${pk}" in table "${this.tableName}".`, 'REPOSITORY_PERSIST_FAILED', undefined, {
                tableName: this.tableName,
                primaryKey: pk,
            });
        }
        return entity;
    }

    /** Flush: no-op for SQLite (data is flushed on each write). */
    public flush(): void {
        // No-op for SQLite
    }

    public async remove(primaryKey: string): Promise<void> {
        const pkCol = this.toSnakeCase(this.primaryKeyField);
        const table = this.tableName as keyof import('./Schema').DatabaseSchema;
        const compiled = qb.deleteFrom(table).where(pkCol as 'uuid', '=', primaryKey).compile();
        await this.executeUpdate(compiled);
    }

    public async clear(): Promise<void> {
        const table = this.tableName as keyof import('./Schema').DatabaseSchema;
        const compiled = qb.deleteFrom(table).compile();
        await this.executeUpdate(compiled);
    }

    /**
     * Full-text search (requires FTS table: {tableName}_fts).
     * Returns entities whose full-text fields match the query.
     * Table and column names are from entity metadata only (this.tableName, this.primaryKeyField, _realFkColumns); the query string is parameterized. Safe from SQL injection.
     */
    public async search(query: string): Promise<TEntity[]> {
        const db = Database.getConnection();
        const ftsTable = `${this.tableName}_fts`;
        const pkCol = this.toSnakeCase(this.primaryKeyField);
        const selectCols = [pkCol, 'data', ...this._realFkColumns.map((c) => c.columnName)]
            .map((c) => `t.${c}`)
            .join(', ');
        const { rows } = await db.execute(
            `SELECT ${selectCols} FROM ${this.tableName} t INNER JOIN ${ftsTable} fts ON t.${pkCol} = fts.${pkCol} WHERE fts MATCH ?`,
            [query],
        );
        const list = Array.isArray(rows) ? (rows as Record<string, unknown>[]) : [];
        return this.hydrateRows(list);
    }

    /** All rows as plain records (for in-memory filter when criteria are nested). */
    private async findAllPlainRecords(): Promise<Record<string, unknown>[]> {
        const table = this.tableName as keyof import('./Schema').DatabaseSchema;
        const orderBy = this.getOrderByColumn();
        const compiled = qb
            .selectFrom(table)
            .selectAll()
            .orderBy(qb.dynamic.ref(orderBy), 'desc')
            .limit(1000)
            .offset(0)
            .compile();
        const rows = await this.executeQuery(compiled);
        return rows.map((row) => this.rowToPlainRecord(row));
    }

    private rowToPlainRecord(row: Record<string, unknown>): Record<string, unknown> {
        const json = (row.data ?? '{}') as string;
        const parsed = JSON.parse(json) as Record<string, unknown>;
        for (const { propertyName, columnName } of this._realFkColumns) {
            if (columnName in row && row[columnName] != null) {
                parsed[propertyName] = row[columnName];
            }
        }
        return this._serializer.unserialize(parsed);
    }

    private async getStoredRecord(pk: string): Promise<Record<string, unknown>> {
        const pkCol = this.toSnakeCase(this.primaryKeyField);
        const table = this.tableName as keyof import('./Schema').DatabaseSchema;
        const compiled = qb.selectFrom(table).selectAll().where(pkCol as 'uuid', '=', pk).compile();
        const rows = await this.executeQuery(compiled);
        return rows.length > 0 ? this.rowToPlainRecord(rows[0]) : {};
    }

    private hydrateFromRow(row: Record<string, unknown>): TEntity {
        const json = (row.data ?? '{}') as string;
        const parsed = JSON.parse(json) as Record<string, unknown>;
        for (const { propertyName, columnName } of this._realFkColumns) {
            if (columnName in row && row[columnName] != null) {
                parsed[propertyName] = row[columnName];
            }
        }
        const unserialized = this._serializer.unserialize(parsed);
        return new this.entityClass(unserialized);
    }

    private hydrateRows(rows: Record<string, unknown>[]): TEntity[] {
        return rows.map((r) => this.hydrateFromRow(r));
    }

    /** True if any criterion value is object or array (requires in-memory isMatch, not SQL). */
    private hasNestedCriteria(criteria: Record<string, unknown>): boolean {
        return Object.values(criteria).some(
            (v) => typeof v === 'object' && v !== null,
        );
    }

    private getOrderByColumn(): string {
        const reader = new MetadataReader(this.entityClass as MetadataConstructor);
        const hasCreatedAt = reader
            .getFields()
            .some((f) => f.getDecoratorName() === 'Column' && f.getFieldName() === 'createdAt' && f.getOptions<ColumnOptions>().index === true);
        return hasCreatedAt ? 'created_at' : this.toSnakeCase(this.primaryKeyField);
    }

    private toSnakeCase(str: string): string {
        return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
    }
}
