import Foundation
import CryptoKit

/**
 * Encryption stream for secure audio recording on iOS/iPadOS
 * 
 * Encrypts audio chunks using AES-256-GCM and writes them to disk. Each chunk is
 * encrypted independently with its own nonce. Audio flows directly from microphone
 * to encrypted disk with no plaintext temporary files.
 * 
 * File format: [4-byte length][12-byte nonce][encrypted data + 16-byte tag]
 * 
 * iOS/iPadOS SPECIFICITY:
 * - Uses FileHandle for file I/O
 * - Uses CryptoKit (AES.GCM.seal) for encryption
 * - Nonce generated by CryptoKit automatically (unique per seal operation)
 * - CryptoKit handles nonce internally (extracted from SealedBox)
 * - write() throws SecureRecorderError
 * - Chunk size written as big-endian Int32
 */
class EncryptionStream {
  private let secretKey: SymmetricKey
  private let outputFile: URL
  private var fileHandle: FileHandle?
  private var inputBuffer = Data()
  
  private static let chunkSizeLength = 4
  private static let encryptionChunkSize = 16 * 1024 // 16KB
  
  internal init(secretKey: Data, outputFile: URL) {
    self.secretKey = SymmetricKey(data: secretKey)
    self.outputFile = outputFile
  }
  
  /**
   * Initialize encryption stream
   * Creates file for writing encrypted chunks
   * 
   * @throws SecureRecorderError if file creation fails
   */
  internal func initialize() throws {
    // Create file if it doesn't exist
    if !FileManager.default.fileExists(atPath: outputFile.path) {
      FileManager.default.createFile(atPath: outputFile.path, contents: nil, attributes: nil)
    }
    
    fileHandle = try FileHandle(forWritingTo: outputFile)
  }
  
  /**
   * Encrypt and write a chunk of data
   * 
   * SECURITY: Each chunk is encrypted independently with its own nonce
   * The sealed box (length + nonce + ciphertext + tag) is written to disk in larger
   * encrypted chunks. Raw audio is buffered in memory and only encrypted/written
   * when the buffer reaches encryptionChunkSize (or on close).
   * 
   * Format: [4-byte length][12-byte nonce][encrypted data + 16-byte tag]
   * The length field indicates the size of (nonce + encrypted data + tag)
   * 
   * @throws SecureRecorderError if stream not initialized or encryption fails
   */
  internal func write(data: Data) throws {
    guard let handle = fileHandle else {
      throw SecureRecorderError.recordingFailed("Encryption stream not initialized")
    }

    // Buffer incoming plaintext audio data in memory
    inputBuffer.append(data)

    // When we've accumulated enough data, encrypt and write to disk
    if inputBuffer.count >= Self.encryptionChunkSize {
      try flushBufferToDisk()
    }
  }
  
  /**
   * Encrypt and write the current buffered plaintext to disk as a single sealed chunk.
   *
   * SECURITY: Each flushed buffer is encrypted independently with its own nonce.
   * Format: [4-byte length][12-byte nonce][encrypted data + 16-byte tag]
   */
  private func flushBufferToDisk() throws {
    guard let handle = fileHandle else {
      throw SecureRecorderError.recordingFailed("Encryption stream not initialized")
    }

    guard !inputBuffer.isEmpty else {
      return
    }

    let plaintext = inputBuffer
    inputBuffer.removeAll(keepingCapacity: true)

    // SECURITY: Encrypt this chunk with AES-256-GCM
    // CryptoKit automatically generates a unique nonce for each seal operation
    do {
      let sealedBox = try AES.GCM.seal(plaintext, using: secretKey)

      // Build sealed box data: [nonce] + [ciphertext] + [tag]
      var sealedBoxData = Data()
      sealedBoxData.append(contentsOf: sealedBox.nonce)
      sealedBoxData.append(sealedBox.ciphertext)
      sealedBoxData.append(sealedBox.tag)

      // Calculate chunk size (nonce + ciphertext + tag)
      let chunkSize = Int32(sealedBoxData.count)

      // Write chunk size header (4 bytes, big-endian - matches Android ByteBuffer.putInt())
      var chunkSizeData = Data()
      withUnsafeBytes(of: chunkSize.bigEndian) { bytes in
        chunkSizeData.append(contentsOf: bytes)
      }

      // SECURITY: Write complete chunk to disk
      // Format: [4-byte chunk size][12-byte nonce][ciphertext][16-byte tag]
      handle.write(chunkSizeData)
      handle.write(sealedBoxData)

    } catch {
      throw SecureRecorderError.recordingFailed("Encryption error: \(error.localizedDescription)")
    }
  }
  
  /**
   * Close encryption stream
   * 
   * Safe to call multiple times (idempotent)
   */
  internal func close() {
    if let handle = fileHandle {
      // Flush any remaining buffered plaintext before closing the stream.
      // Errors are ignored here to keep close() idempotent and non-throwing.
      try? flushBufferToDisk()
      handle.closeFile()
      fileHandle = nil
    }
  }
}
