import Foundation
import CryptoKit

/**
 * Encryption stream for secure audio recording on iOS/iPadOS
 * 
 * Encrypts audio chunks using AES-256-GCM and writes them to disk. Each chunk is
 * encrypted independently with its own nonce. Audio flows directly from microphone
 * to encrypted disk with no plaintext temporary files.
 * 
 * File format: [4-byte length][12-byte nonce][encrypted data + 16-byte tag]
 * 
 * iOS/iPadOS SPECIFICITY:
 * - Uses FileHandle for file I/O
 * - Uses CryptoKit (AES.GCM.seal) for encryption
 * - Nonce generated by CryptoKit automatically (unique per seal operation)
 * - CryptoKit handles nonce internally (extracted from SealedBox)
 * - write() throws SecureRecorderError
 * - Chunk size written as big-endian Int32
 */
class EncryptionStream {
  // Private properties
  private let secretKey: SymmetricKey
  private let outputFile: URL
  private var fileHandle: FileHandle?
  
  private static let chunkSizeLength = 4 // 4 bytes for Int32 (chunk size header)
  
  // Initializer
  internal init(secretKey: Data, outputFile: URL) {
    self.secretKey = SymmetricKey(data: secretKey)
    self.outputFile = outputFile
  }
  
  // Internal methods
  /**
   * Initialize encryption stream
   * Creates file for writing encrypted chunks
   * 
   * @throws SecureRecorderError if file creation fails
   */
  internal func initialize() throws {
    // Create file if it doesn't exist
    if !FileManager.default.fileExists(atPath: outputFile.path) {
      FileManager.default.createFile(atPath: outputFile.path, contents: nil, attributes: nil)
    }
    
    fileHandle = try FileHandle(forWritingTo: outputFile)
  }
  
  /**
   * Encrypt and write a chunk of data
   * 
   * SECURITY: Each chunk is encrypted independently with its own nonce
   * The sealed box (length + nonce + ciphertext + tag) is written immediately to disk
   * No plaintext buffering in memory beyond the current chunk
   * 
   * Format: [4-byte length][12-byte nonce][encrypted data + 16-byte tag]
   * The length field indicates the size of (nonce + encrypted data + tag)
   * 
   * @throws SecureRecorderError if stream not initialized or encryption fails
   */
  internal func write(data: Data) throws {
    guard let handle = fileHandle else {
      throw SecureRecorderError.recordingFailed("Encryption stream not initialized")
    }
    
    // SECURITY: Encrypt this chunk with AES-256-GCM
    // CryptoKit automatically generates a unique nonce for each seal operation
    do {
      let sealedBox = try AES.GCM.seal(data, using: secretKey)
      
      // Build sealed box data: [nonce] + [ciphertext] + [tag]
      var sealedBoxData = Data()
      sealedBoxData.append(contentsOf: sealedBox.nonce)
      sealedBoxData.append(sealedBox.ciphertext)
      sealedBoxData.append(sealedBox.tag)
      
      // Calculate chunk size (nonce + ciphertext + tag)
      let chunkSize = Int32(sealedBoxData.count)
      
      // Write chunk size header (4 bytes, big-endian - matches Android ByteBuffer.putInt())
      var chunkSizeData = Data()
      withUnsafeBytes(of: chunkSize.bigEndian) { bytes in
        chunkSizeData.append(contentsOf: bytes)
      }
      
      // SECURITY: Write complete chunk to disk immediately
      // Format: [4-byte chunk size][12-byte nonce][ciphertext][16-byte tag]
      handle.write(chunkSizeData)
      handle.write(sealedBoxData)
      
    } catch {
      throw SecureRecorderError.recordingFailed("Encryption error: \(error.localizedDescription)")
    }
  }
  
  /**
   * Close encryption stream
   * 
   * Safe to call multiple times (idempotent)
   */
  internal func close() {
    if let handle = fileHandle {
      handle.closeFile()
      fileHandle = nil
    }
  }
}
