/**
 * Recording error types
 * Enum for categorizing recording-related errors
 */

export enum RecordingErrorType {
    PERMISSION_DENIED = 'PERMISSION_DENIED',
    RECORDER_NOT_INITIALIZED = 'RECORDER_NOT_INITIALIZED',
    NO_ACTIVE_RECORDING = 'NO_ACTIVE_RECORDING',
    RECORDING_URI_UNAVAILABLE = 'RECORDING_URI_UNAVAILABLE',
    FILE_OPERATION_FAILED = 'FILE_OPERATION_FAILED',
    RECORDING_FAILED = 'RECORDING_FAILED',
    PERMISSION_REQUEST_FAILED = 'PERMISSION_REQUEST_FAILED',
}
