/**
 * Error codes for SecureRecorder operations.
 * Type-safe enum for all possible error conditions.
 */
export enum ErrorCode {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  RECORDING_IN_PROGRESS = 'RECORDING_IN_PROGRESS',
  NO_RECORDING_IN_PROGRESS = 'NO_RECORDING_IN_PROGRESS',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  INITIALIZATION_FAILED = 'INITIALIZATION_FAILED',
  KEYCHAIN_ERROR = 'KEYCHAIN_ERROR',
  RECORDING_FAILED = 'RECORDING_FAILED',
  STOP_FAILED = 'STOP_FAILED',
  RECORDER_STOPPED = 'RECORDER_STOPPED',
  INVALID_SESSION_ID = 'INVALID_SESSION_ID',
  DECRYPTION_FAILED = 'DECRYPTION_FAILED',
  PERMISSION_CHECK_FAILED = 'PERMISSION_CHECK_FAILED',
  PERMISSION_REQUEST_FAILED = 'PERMISSION_REQUEST_FAILED',
}
