/* do not change this file, it is auto generated by storybook. */
import { start, updateView, type View } from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';
import '@storybook/addon-ondevice-notes/register';

const normalizedStories = [
    {
        titlePrefix: '',
        directory: './stories',
        files: '**/*.stories.@(js|jsx|ts|tsx|mdx)',
        importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx|mdx))$/,
        // @ts-expect-error
        req: require.context('../stories', true, /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx|mdx))$/),
    },
];

declare global {
    var view: View;
    var STORIES: typeof normalizedStories;
}

const annotations = [require('./preview'), require('@storybook/react-native/preview')];

global.STORIES = normalizedStories;

// @ts-expect-error
module?.hot?.accept?.();

if (!global.view) {
    global.view = start({
        annotations,
        storyEntries: normalizedStories,
    });
} else {
    updateView(global.view, annotations, normalizedStories);
}

export const view: View = global.view;
